# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: cairo-snake
version: '0.0.0'
github: "bigos/cairo-snake"
license: MIT
author: "Jacek Podkanski"
maintainer: "Jacek Podkanski"
# synopsis: A new Haskeleton package.
# description: cairo-snake is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  cairo-snake:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - cairo-snake
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  cairo-snake-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - cairo-snake
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  cairo-snake-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - cairo-snake
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
